### ISSUE TITLE
Minutes Meeting file

### ISSUE THREAD

**Issue by Alexis07Bernier** [PaulYH/GOATed_with_the_SAUCE-soen341project2023#10]
I think you should review your minutes meeting file as this seem a bit too cluttered and verbose (hard to read) https://www.merriam-webster.com/dictionary/verbose. I'm playing with you but yeah, I think bullet point would be ideal. Thanks!

**Comment by PaulYH** [comment]
Please also add a copy of what's written in the minutes file to the GitHub wiki for easier access and readability

**Comment by Alexis07Bernier** [comment]
@Patacorn Any updates on the meeting file?
