### ISSUE TITLE
TASK: Add PDF Upload Component to Student Profile Page

### ISSUE THREAD

**Issue by PaulYH** [PaulYH/GOATed_with_the_SAUCE-soen341project2023#16]
The Student user should be able to upload a pdf to the profile in the profile page, so as not to have to upload it for every application.

Back end detailed in #17

**Comment by Alexis07Bernier** [comment]
Added PDF Upload page (Frontend). Decided to create separate pdf upload page from the profile page so it can be accessed from the application page
