### ISSUE TITLE
TASK: Show/Hide App Features Based on User Role 

### ISSUE THREAD

**Issue by tati-b** [PaulYH/GOATed_with_the_SAUCE-soen341project2023#18]
Overall, the Student user should be able to edit user profile, view job posts, apply to job posts, and view one's existing applications. The Employer should be able to edit user profile, create new job posts, view one's existing job posts, view all applications to one's job posts, and change an existing application's status.

The admin should be able to do everything the above user types can do, in addition to being able to delete any applications and job posts.

**Comment by Alexis07Bernier** [comment]
Added to the pdf upload to hide from employers

**Comment by PaulYH** [comment]
This is partially implemented for job postings and user profile, and will likely be an ongoing task as the sprints go by.
