### ISSUE TITLE
US - 02 Summary of Job Applications

### ISSUE THREAD

**Issue by tati-b** [PaulYH/GOATed_with_the_SAUCE-soen341project2023#4]
As a recruiter/employer, I would like to have a simplified version (a summary) of the website with all job applications so that it will be easier and faster to access them. I would like see a short description of every job application in one page. In order to see a detailed description, the recruiter can click on the application and more details will be displayed. 

**Priority:** LOW
The reason why the priority is low is because it is not a core feature. It is preferable to have it for the more convenient use of the website.  

**Story Points:** 4
All parts of the project are involved. 

**Acceptance Tests**
-
**Checking the Job Application**
1. I log in into my employer account. 
2. I click on job applications button.
3. I am directed to the application page with the list of applications.
4. I see the list of applications along with names and date of application.
5. I click on interested application and I see the short description of it.
6. I want to see the full information about the person who applied ,therefore I click on it in order to get more details.
7. I am directed to the application page and I see more details about the person who applied, his/her resume and other relevant information.

**Comment by PaulYH** [comment]
In this "preview" summary the employer can view:

- Student Name
- Student Program
- Graduation Date
- Previous Experience

**Comment by tati-b** [comment]
Done!
